name: Build, Push and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::670682107839:role/GitHubActions-DevOpsPortfolio
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-portfolio
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        env:
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/devops-portfolio:${{ github.sha }}
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-009343064307f284a" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy DevOps portfolio" \
            --parameters "commands=[
              \"aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 670682107839.dkr.ecr.ap-south-1.amazonaws.com\",
              \"sudo docker pull $IMAGE_URI\",
              \"sudo docker stop devops-portfolio || true\",
              \"sudo docker rm devops-portfolio || true\",
              \"sudo docker run -d --name devops-portfolio -p 8080:80 $IMAGE_URI\"
            ]" \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "i-009343064307f284a"

          echo "Deployment completed successfully!"